-- Procedure code

-- SET AUTO OFF;

CREATE OR REPLACE PROCEDURE RAISE_SALARY(MSG OUT VARCHAR2)
IS

    SALARY DEPOSIT.BAL%TYPE;

BEGIN

    UPDATE DEPOSIT SET BAL = BAL * 1.2;

    SELECT SUM(BAL) INTO SALARY FROM DEPOSIT;

    IF SALARY > 100000 THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('rollback.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Raise complete');

    END IF;  
    
END;


-- Excecution code

DECLARE
    TEMP VARCHAR2(10);
BEGIN
    RAISE_SALARY(TEMP);
END;

-- SELECT * FROM DEPOSIT;