-- FUNCTION CODE

CREATE OR REPLACE FUNCTION FINE(ANO IN DEPOSIT.ACC_NO%TYPE)
RETURN NUMBER 
IS

    BALANCE DEPOSIT.BAL%TYPE;

BEGIN

    SELECT BAL INTO BALANCE FROM DEPOSIT WHERE ANO = ACC_NO;

    IF BALANCE < 1500 THEN
    UPDATE DEPOSIT SET BAL = BAL - 100 WHERE ANO = ACC_NO; 
        DBMS_OUTPUT.PUT_LINE('Fine is deduct because of low balance');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Account has sufficent balance');
    END IF;

    RETURN 0;
END;

-- EXECUTION CODE

DECLARE

    ANO DEPOSIT.ACC_NO%TYPE;
    ANS DEPOSIT.BAL%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter account number');
    ANO := :ANO;

    ANS := FINE(ANO);

END;

-- UPDATE DEPOSIT SET BAL = 200 WHERE ACC_NO = 7844;

-- SET AUTO OFF;

-- ROLLBACK;

-- SELECT * FROM DEPOSIT;