-- CODE FOR THE TRIGGER

CREATE OR REPLACE TRIGGER INSERT_MSG 
AFTER
INSERT 
ON DEPOSIT
REFERENCING NEW AS NEW
FOR EACH ROW 
BEGIN

    DBMS_OUTPUT.PUT_LINE('Row inserted successfully');

END;

-- EXCECUTION CODE

DECLARE

    U_NAME DEPOSIT.C_NAME%TYPE;
    BRANCH DEPOSIT.B_NAME%TYPE;
    BALANCE DEPOSIT.BAL%TYPE;
    ANO DEPOSIT.ACC_NO%TYPE;
    EMAIL DEPOSIT.EMAIL_ID%TYPE;
    NO DEPOSIT.MOB_NO%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter name');
    U_NAME := :U_NAME;

    DBMS_OUTPUT.PUT_LINE('Enter branch name');
    BRANCH := :BRANCH;

    DBMS_OUTPUT.PUT_LINE('Enter balance');
    BALANCE := :BALAMCE;

    DBMS_OUTPUT.PUT_LINE('Enter account no');
    ANO := :ANO;

    DBMS_OUTPUT.PUT_LINE('Enter email id');
    EMAIL := :EMAIL;
    
    DBMS_OUTPUT.PUT_LINE('Enter mobile no');
    NO := :NO;
    
    INSERT INTO DEPOSIT VALUES(U_NAME, BRANCH, BALANCE, ANO, EMAIL, NO);

END;

-- SELECT * FROM DEPOSIT;