-- CODE FOR TRIGGER

CREATE OR REPLACE TRIGGER LESS_BAL 
BEFORE  
UPDATE
ON DEPOSIT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE 

    BALANCE DEPOSIT.ACC_NO%TYPE;

BEGIN

    SELECT BAL INTO BALANCE FROM DEPOSIT WHERE :NEW.ACC_NO = :OLD.ACC_NO;

    IF :NEW.BAL < :OLD.BAL THEN  
        DBMS_OUTPUT.PUT_LINE('You doesn''t have sufficent balance');
    END IF;

END;

-- EXCECUTION CODE

DECLARE 

    ANO DEPOSIT.ACC_NO%TYPE;
    AMOUNT DEPOSIT.BAL%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter you account number');
    ANO := :ANO;

    DBMS_OUTPUT.PUT_LINE('Enter amount');
    AMOUNT := :AMOUNT;

    UPDATE DEPOSIT SET BAL = BAL - AMOUNT WHERE ACC_NO = ANO;

END;

-- SELECT * FROM DEPOSIT;

-- DROP TRIGGER LESS_BAL;