DECLARE

    EX_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(EX_NULL, -1400);

    INVALID_DIGIT EXCEPTION;

    ANO DEPOSIT.ACC_NO%TYPE;
    BALANCE DEPOSIT.BAL%TYPE;
    BRANCH DEPOSIT.B_NAME%TYPE;
    CUSTOMER DEPOSIT.C_NAME%TYPE;
    EMAIL DEPOSIT.EMAIL_ID%TYPE;
    PHONE_NO DEPOSIT.MOB_NO%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter account number');
    ANO := :ANO;
    DBMS_OUTPUT.PUT_LINE('Enter balance');
    BALANCE := :BALANCE;
    DBMS_OUTPUT.PUT_LINE('Enter branch name');
    BRANCH := :BARANCH;
    DBMS_OUTPUT.PUT_LINE('Enter customer name');
    CUSTOMER := :CUSTOMER;
    DBMS_OUTPUT.PUT_LINE('Enter email id');
    EMAIL := :EMAIL;
    DBMS_OUTPUT.PUT_LINE('Enter mobile no.');
    PHONE_NO := :PHONE_NO;


    IF PHONE_NO > 9999999999 AND PHONE_NO < 0000000000 THEN
        RAISE INVALID_DIGIT;
    ELSE
        INSERT INTO DEPOSIT VALUES(CUSTOMER, BRANCH, BALANCE, ANO, EMAIL, PHONE_NO);
    END IF;



EXCEPTION

    WHEN EX_NULL THEN
        DBMS_OUTPUT.PUT_LINE('Account number can''t be null');

    WHEN DUP_VAL_ON_INDEX THEN  
        DBMS_OUTPUT.PUT_LINE('Given mobile number is already exist');

    WHEN INVALID_DIGIT THEN
        DBMS_OUTPUT.PUT_LINE('Mobile number should contain maximum 10 digits');

END;

-- SELECT * FROM DEPOSIT;

-- DELETE FROM DEPOSIT WHERE C_NAME = 'RAMADATTI';