-- PACKAGE SPECIFICATION CODE

CREATE OR REPLACE PACKAGE PKG_ACCOUNT
IS
    PROCEDURE DEBIT_ACC (ACCOUNT_NO IN DEPOSIT.ACC_NO%TYPE, AMOUNT IN DEPOSIT.BAL%TYPE);
    FUNCTION GET_BALANCE(ACCOUNT_NO IN DEPOSIT.ACC_NO%TYPE)
    RETURN DEPOSIT.BAL%TYPE;

END PKG_ACCOUNT;

-- PACKAGE BODY CODE

CREATE OR REPLACE PACKAGE BODY PKG_ACCOUNT
IS 

    PROCEDURE DEBIT_ACC(ACCOUNT_NO IN DEPOSIT.ACC_NO%TYPE, AMOUNT IN DEPOSIT.BAL%TYPE)
    IS

        ANO DEPOSIT.ACC_NO%TYPE := ACCOUNT_NO;
        DEBIT DEPOSIT.BAL%TYPE := AMOUNT;

    BEGIN

        UPDATE DEPOSIT SET BAL = BAL - DEBIT WHERE ACC_NO = ANO;
        DBMS_OUTPUT.PUT_LINE('Debit has been successful');

    END DEBIT_ACC;

    FUNCTION GET_BALANCE(ACCOUNT_NO IN DEPOSIT.ACC_NO%TYPE)
    RETURN DEPOSIT.BAL%TYPE
    IS

        ANO DEPOSIT.ACC_NO%TYPE := ACCOUNT_NO;
        BALANCE DEPOSIT.BAL%TYPE;
    
    BEGIN

        SELECT BAL INTO BALANCE FROM DEPOSIT WHERE ACC_NO = ANO;
        RETURN BALANCE;

    END GET_BALANCE;

END PKG_ACCOUNT;

-- EXCECUTION CODE

DECLARE 

    ANO DEPOSIT.ACC_NO%TYPE;
    BALANCE DEPOSIT.BAL%TYPE;
    AMOUNT DEPOSIT.BAL%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter account no');
    ANO := :ANO;

    DBMS_OUTPUT.PUT_LINE('Enter amount to debit');
    AMOUNT := :AMOUNT;

    PKG_ACCOUNT.DEBIT_ACC(ANO, AMOUNT);
    BALANCE := PKG_ACCOUNT.GET_BALANCE(ANO);

    DBMS_OUTPUT.PUT_LINE('Balance of your account is: ' || BALANCE);

END;