-- PKCKAGE CODE

CREATE OR REPLACE PACKAGE PKG_LOAN
IS 

    PROCEDURE DEPT_LOAN_ACC(ACCOUNT_NO IN LOAN.ACC_NO%TYPE, AMOUNT IN LOAN.AMOUNT%TYPE);

    FUNCTION DELETE_LOAN_ACC(ACCOUNT_NO IN LOAN.ACC_NO%TYPE)
    RETURN NUMBER;

END PKG_LOAN;

-- CODE OF BODY OF PACKAGE

CREATE OR REPLACE PACKAGE BODY PKG_LOAN
IS
    PROCEDURE DEPT_LOAN_ACC(ACCOUNT_NO IN LOAN.ACC_NO%TYPE, AMOUNT IN LOAN.AMOUNT%TYPE)
    IS

        ANO LOAN.ACC_NO%TYPE := ACCOUNT_NO;
        DEPT_CASH LOAN.AMOUNT%TYPE := AMOUNT;

    BEGIN
    
        UPDATE LOAN SET AMOUNT = AMOUNT + DEPT_CASH WHERE ACC_NO = ANO;
        DBMS_OUTPUT.PUT_LINE('Account has been update successful');

    END DEPT_LOAN_ACC;

    FUNCTION DELETE_LOAN_ACC(ACCOUNT_NO IN LOAN.ACC_NO%TYPE)
    RETURN NUMBER
    IS

        ANO LOAN.ACC_NO%TYPE := ACCOUNT_NO;

    BEGIN

        DELETE FROM LOAN WHERE ANO = LOAN.ACC_NO;
        DBMS_OUTPUT.PUT_LINE('Account has been deleted');
        RETURN 0;

    END DELETE_LOAN_ACC;

END PKG_LOAN;


-- EXCECUTION CODE

DECLARE

    ANO LOAN.ACC_NO%TYPE;
    AMOUNT LOAN.AMOUNT%TYPE;
    TEMP LOAN.AMOUNT%TYPE;
    

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter your account no');
    ANO := :ANO;

    DBMS_OUTPUT.PUT_LINE('Enter amount to deposit');
    AMOUNT := :AMOUNT;

    PKG_LOAN.DEPT_LOAN_ACC(ANO, AMOUNT);
    TEMP := PKG_LOAN.DELETE_LOAN_ACC(ANO);
    
END;

-- INSERT INTO LOAN VALUES('4545', 'Dustin', 12000, '7844');

SELECT * FROM LOAN;