DECLARE

    ANO DEPOSIT.ACC_NO%TYPE;
    AMOUNT DEPOSIT.BAL%TYPE;
    BAL_CHECK DEPOSIT.BAL%TYPE;
BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter your account number');
    ANO := :ANO;

    DBMS_OUTPUT.PUT_LINE('Enter your Amount');
    AMOUNT := :AMOUNT;

    SELECT BAL INTO BAL_CHECK FROM DEPOSIT WHERE ANO = ACC_NO;

    UPDATE DEPOSIT SET DEPOSIT.BAL = DEPOSIT.BAL - AMOUNT 

    IF BAL_CHECK <= AMOUNT THEN
        ROLLBACK;
    END IF

END;

-- SELECT * FROM DEPOSIT;

-- INSERT INTO DEPOSIT VALUES('Dustin','New Jersy',6600,'7844','Dustin@gmail.com','77568');

-- DELETE FROM DEPOSIT WHERE C_NAME = 'Dustin'; 
