DECLARE

    PERCENTAGE DECIMAL;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Enter percentage');
    PERCENTAGE := :PERCENTAGE;

    IF PERCENTAGE >= 70 THEN
        DBMS_OUTPUT.PUT_LINE('Distinctions');
    ELSIF PERCENTAGE >= 60 AND PERCENTAGE < 70 THEN
        DBMS_OUTPUT.PUT_LINE('First Class');
    ELSIF PERCENTAGE >= 50 AND PERCENTAGE < 60 THEN 
        DBMS_OUTPUT.PUT_LINE('Second Class');
    ELSIF PERCENTAGE >= 40 AND PERCENTAGE < 50 THEN
        DBMS_OUTPUT.PUT_LINE('Pass Class');
    ELSIF PERCENTAGE < 40 THEN
        DBMS_OUTPUT.PUT_LINE('NEED IMPROVRMENT');
    END IF;
END;